import pyperclip
html = """\
    <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;"><span style="font-size: 12px;">
        <div class="TableContainer  BCX2 SCXW14658481">
            <div class="WACAltTextDescribedBy  BCX2 SCXW14658481" style="line-height: 1;"><br></div>
            <table border="1" class="Table TableWordWrap  BCX2 SCXW14658481" data-tablelook="1184" data-tablestyle="MsoNormalTable" style="border-collapse: collapse; background: transparent none repeat scroll 0% 0%; border-spacing: 0px;">
                <tbody class="BCX2 SCXW14658481">
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 20px;">
                        <td class="BCX2 SCXW14658481" colspan="5" data-celllook="69905" style="background-color: rgb(255, 192, 0); border-color: rgb(31, 73, 125) rgb(31, 73, 125) rgb(31, 78, 121); border-style: solid; border-width: 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: center; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">CRITSIT NOTIFICATION</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335551550":2,"335551620":2,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 19px;">
                        <td class="BCX2 SCXW14658481" colspan="5" data-celllook="69905" style="background-color: rgb(255, 0, 0); border-color: currentcolor rgb(31, 73, 125) rgb(31, 78, 121); border-style: none solid solid; border-width: 0px 2px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: center; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Status:</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Times New Roman, Times New Roman_EmbeddedFont, Times New Roman_MSFontService, serif; line-height: 19.95px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Times New Roman, Times New Roman_EmbeddedFont, Times New Roman_MSFontService, serif; line-height: 19.95px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">In Progress</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335551550":2,"335551620":2,"335559739":0,"335559740":252}}' style="line-height: 19.95px; font-family: Times New Roman, Times New Roman_EmbeddedFont, Times New Roman_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 19px;">
                        <td class="BCX2 SCXW14658481" colspan="5" data-celllook="69905" style="background-color: rgb(149, 179, 215); border-color: currentcolor rgb(31, 73, 125) rgb(31, 78, 121); border-style: none solid solid; border-width: 0px 2px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Incident Description&nbsp;</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 15px;">
                        <td class="BCX2 SCXW14658481" colspan="5" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0); border-style: none solid solid; border-width: 0px 2px 1px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Application/Service/Major Component</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(255, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">*</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">:</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;{var1}</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 15px;">
                        <td class="BCX2 SCXW14658481" colspan="5" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0); border-style: none solid solid; border-width: 0px 2px 1px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Issue</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(255, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">*</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">:</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;{var2}</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 15px;">
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(31, 78, 121) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 2px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Impact:  </span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Internal/External</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="4" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 78, 121) rgb(31, 78, 121) currentcolor; border-style: none solid solid none; border-width: 0px 2px 2px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 578px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">External</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 15px;">
                        <td class="BCX2 SCXW14658481" colspan="5" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 78, 121) rgb(31, 78, 121) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 2px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 14px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Note: KITT notifications (for Sales/Marketing communication) will be automatically sent for every&nbsp;</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">external&nbsp;</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">incident. Created by Tech Support mgmt.&nbsp;</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 14px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 5px;">
                        <td class="BCX2 SCXW14658481" colspan="5" data-celllook="69905" style="background-color: rgb(141, 179, 226); border-color: currentcolor rgb(31, 78, 121) rgb(0, 0, 0) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 2px 1px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Incident Details</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 5px;">
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(0, 0, 0) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 1px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="auto" lang="EN-US" style="font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Incident Severity (</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Sev</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;1/2/3)</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">:</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="4" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 578px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 14px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 5px;">
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(0, 0, 0) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 1px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Incident&nbsp;</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="auto" lang="EN-US" style="font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Reported</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Date/</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2  BCX2 SCXW14658481" style="background-color: inherit;">Time:</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(255, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2  BCX2 SCXW14658481" style="background-color: inherit;">*</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 190px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;{var3}</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 218px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Resolution Date</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(31, 73, 125); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">/</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Time</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="2" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 170px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: center; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335551550":2,"335551620":2,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 5px;">
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(0, 0, 0) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 1px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Customer Impact Start Date/Time: (if known)</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 190px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 218px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Customer Impact Resolution&nbsp;</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 13px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">(if different)</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 13px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="2" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 170px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: center; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335551550":2,"335551620":2,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 5px;">
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(0, 0, 0) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 1px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Incident ID #</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="auto" lang="EN-US" style="font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">(if available)</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="4" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 578px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 11px;">
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(0, 0, 0) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 1px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Reported By:</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="4" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(0, 0, 0) currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 578px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 31px;">
                        <td class="BCX2 SCXW14658481" colspan="2" data-celllook="69905" style="background-color: rgb(141, 180, 226); border-color: currentcolor rgb(31, 78, 121) rgb(31, 78, 121) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 2px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 417px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="auto" lang="EN-US" style="font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Bridge/</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Incident Manager</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">(IM) Details</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="3" data-celllook="69905" style="background-color: rgb(141, 180, 226); border-color: currentcolor rgb(31, 73, 125) currentcolor currentcolor; border-style: none solid solid none; border-width: 0px 2px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 388px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Resources/Technology Details</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 19px;">
                        <td class="BCX2 SCXW14658481" colspan="2" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor currentcolor rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 1px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 417px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="2" data-celllook="0" style="background-color: transparent; border: 0px none; vertical-align: bottom; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Times New Roman, Times New Roman_EmbeddedFont, Times New Roman_MSFontService, serif; line-height: 19px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Service</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 19px; font-family: Times New Roman, Times New Roman_EmbeddedFont, Times New Roman_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) currentcolor currentcolor; border-style: none solid solid; border-width: 0px 2px 1px 1px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 161px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: center; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335551550":2,"335551620":2,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 41px;">
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor currentcolor rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 1px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Email ID</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor; border-style: none solid solid none; border-width: 0px 1px 1px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 190px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: justify; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">n/a</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335551550":6,"335551620":6,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="2" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(31, 78, 121); border-style: solid solid solid none; border-width: 1px 1px 2px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Team/Engineer</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(31, 78, 121) currentcolor; border-style: none solid solid none; border-width: 0px 2px 2px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 161px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: center; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335551550":2,"335551620":2,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 45px;">
                        <td class="BCX2 SCXW14658481" colspan="2" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(31, 78, 121) rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 1px 2px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 417px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Slack&nbsp;</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2  BCX2 SCXW14658481" style="background-color: inherit;">Subchannel</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2  BCX2 SCXW14658481" style="background-color: inherit;">:</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(255, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2  BCX2 SCXW14658481" style="background-color: inherit;">*</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;{var4}</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" colspan="2" data-celllook="4369" style="background-color: transparent; border-color: currentcolor currentcolor rgb(31, 78, 121); border-style: none solid solid none; border-width: 0px 1px 2px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 227px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;&nbsp;</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Business/System Owner</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                        <td class="BCX2 SCXW14658481" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125) rgb(31, 78, 121) currentcolor; border-style: none solid solid none; border-width: 0px 2px 2px 0px; border-image: none 100% / 1 / 0 stretch; vertical-align: bottom; width: 161px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: center; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335551550":2,"335551620":2,"335559739":0,"335559740":240}}' style="line-height: 18px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 84px;">
                        <td class="BCX2 SCXW14658481 " colspan="5" data-celllook="69905" style="background-color: rgb(142, 170, 219); border-color: currentcolor rgb(31, 78, 121) rgb(31, 78, 121); border-style: none solid solid; border-width: 0px 2px 2px; border-image: none 100% / 1 / 0 stretch; vertical-align: top; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun Underlined  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; text-decoration: underline; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Issue Description (and u</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">pdates</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">)</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">:</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                                <div class="ListContainerWrapper  BCX2 SCXW14658481">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 14.7px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(255, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">*</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="auto" lang="EN-US" style="font-style: italic; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; line-height: 14.7px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Initial report:</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 14.7px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                </div>
                                <div class="ListContainerWrapper  BCX2 SCXW14658481">
                                    <ul class="BulletListStyle1  BCX2 SCXW14658481">
                                        <li>{var5}</li>
                                        <li><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></li>
                                        <li class="OutlineElement Ltr  BCX2 SCXW14658481" data-aria-level="1" data-aria-posinset="6" data-font="Symbol" data-leveltext="" data-listid="3" style="display: block; margin-left: 24px; font-size: 11pt; font-family: Calibri, Calibri_MSFontService, sans-serif; vertical-align: baseline; direction: ltr;">
                                            <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 18.9px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr class="TableRow  BCX2 SCXW14658481" style="height: 35px;">
                        <td class="BCX2 SCXW14658481" colspan="5" data-celllook="4369" style="background-color: transparent; border-color: currentcolor rgb(31, 73, 125); border-style: none solid solid; border-width: 0px 2px 1px; border-image: none 100% / 1 / 0 stretch; vertical-align: middle; width: 805px;">
                            <div class="TableCellContent  BCX2 SCXW14658481" style="padding: 0px 7px;">
                                <div class="OutlineElement Ltr  BCX2 SCXW14658481" style="direction: ltr;">
                                    <p class="Paragraph  BCX2 SCXW14658481" style="font-weight: normal; font-style: normal; vertical-align: baseline; background-color: transparent; color: windowtext; text-align: left; margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-right: 0px; text-indent: 0px; line-height: 1;"><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">Next&nbsp;</span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2  BCX2 SCXW14658481" style="background-color: inherit;">Update:</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(255, 0, 0); font-weight: bold; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2  BCX2 SCXW14658481" style="background-color: inherit;">*</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp; </span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&nbsp;</span><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">In 30 minutes</span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="none" lang="EN-US" style="color: rgb(0, 0, 0); font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 18.9px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;"> </span></span><span class="TextRun  BCX2 SCXW14658481" data-contrast="auto" lang="EN-US" style="font-style: italic; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif; line-height: 14.7px;"><span class="NormalTextRun  BCX2 SCXW14658481" style="background-color: inherit;">&lt;every 30 minutes or sooner if important information becomes available&gt;</span></span><span class="EOP  BCX2 SCXW14658481" data-ccp-props='{{"201341983":0,"335559739":0,"335559740":252}}' style="line-height: 14.7px; font-family: Book Antiqua, Book Antiqua_EmbeddedFont, Book Antiqua_MSFontService, serif;">&nbsp;</span></p>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </span></div>
"""

rep1 = html.replace('line-height: 18.9px','line-height: 17.5px')
# rep2 = rep1.replace('}','}}')
# print(rep2)
pyperclip.copy(rep1)